name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 16
          - 18
          - 18.18
          - 20
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        exclude:
          - node: 16
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
        env:
          # https://github.com/actions/setup-node/issues/531#issuecomment-1819151412
          SKIP_YARN_COREPACK_CHECK: 1
          YARN_IGNORE_NODE: 1

      - name: Install Dependencies
        run: yarn --immutable
        env:
          SKIP_YARN_COREPACK_CHECK: 1
          YARN_IGNORE_NODE: 1

      - name: Build, Lint and Test
        run: yarn cross-env SYNCKIT_TIMEOUT=10000 concurrently -r -m 1 yarn:build yarn:lint yarn:test
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true
          SKIP_YARN_COREPACK_CHECK: 1
          YARN_IGNORE_NODE: 1

      - name: Benchmark
        run: yarn benchmark
        continue-on-error: ${{ matrix.node == 20 }}
        env:
          SKIP_YARN_COREPACK_CHECK: 1
          YARN_IGNORE_NODE: 1

      - name: Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.node != 20 }}
